__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]

# Override dataset paths for egg detection
dataset:
  train:
    img_folder: '/active-1/Omlet_IP/coco_egg_dataset/train'
    ann_file: '/active-1/Omlet_IP/coco_egg_dataset/annotations/instances_train.json'
  val:
    img_folder: '/active-1/Omlet_IP/coco_egg_dataset/val'
    ann_file: '/active-1/Omlet_IP/coco_egg_dataset/annotations/instances_val.json'

# Override number of classes
num_classes: 1

output_dir: '/home/ewan/omlet-server-egg-det/outputs/egg_detection_training'


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True


HybridEncoder:
  in_channels: [128, 256, 512]
  hidden_dim: 256
  expansion: 0.5


RTDETRTransformerv2:
  num_layers: 3


epoches: 120 

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      - Resize: {size: [640, 640]}
      - RandomHorizontalFlip: {p: 0.5}
      - RandomPhotometricDistort: {}
      - ToImageTensor: {}
      - ConvertBox: {fmt: cxcywh, normalize: true}
  batch_size: 8
  collate_fn:
    scales: ~

val_dataloader:
  dataset:
    transforms:
      - Resize: {size: [640, 640]}
      - ToImageTensor: {}
      - ConvertBox: {fmt: cxcywh, normalize: true}
  batch_size: 8