# Simple RT-DETR config for egg detection without complex includes
yaml_cfg:
  task: detection

# Model configuration
RTDETR:
  use_focal_loss: True

PResNet:
  depth: 18
  variant: d
  freeze_at: -1
  freeze_norm: False
  pretrained: True
  return_idx: [1, 2, 3]

HybridEncoder:
  in_channels: [128, 256, 512]
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  expansion: 0.5

RTDETRTransformerv2:
  feat_channels: 256
  feat_strides: [8, 16, 32]
  hidden_dim: 256
  num_levels: 3
  num_layers: 3
  num_queries: 300
  num_classes: 1

# Dataset configuration
num_classes: 1

dataset:
  train:
    img_folder: '/active-1/Omlet_IP/coco_egg_dataset/train'
    ann_file: '/active-1/Omlet_IP/coco_egg_dataset/annotations/instances_train.json'
  val:
    img_folder: '/active-1/Omlet_IP/coco_egg_dataset/val'
    ann_file: '/active-1/Omlet_IP/coco_egg_dataset/annotations/instances_val.json'

# Training configuration
epoches: 120
print_freq: 50
output_dir: '/home/ewan/omlet-server-egg-det/outputs/egg_detection_training'

# Data loading
train_dataloader:
  batch_size: 8
  shuffle: True
  num_workers: 4
  drop_last: True
  dataset:
    transforms:
      - RandomPhotometricDistort: {}
      - RandomZoomOut: {max_scale: 2.0, p: 0.5}
      - RandomCrop: {min_ious: [0.1, 0.3, 0.5, 0.7, 0.9, 1.0], p: 0.5}
      - Resize: {size: [640, 640]}
      - RandomHorizontalFlip: {p: 0.5}
      - SanitizeBoundingBox: {min_size: 1}
      - ToImageTensor: {}
      - ConvertBox: {fmt: cxcywh, normalize: true}

val_dataloader:
  batch_size: 8
  shuffle: False
  num_workers: 4
  drop_last: False
  dataset:
    transforms:
      - Resize: {size: [640, 640]}
      - ToImageTensor: {}
      - ConvertBox: {fmt: cxcywh, normalize: true}

# Optimizer configuration
LR: 0.0001
optimizer:
  type: AdamW
  lr: 0.0001
  weight_decay: 0.0001
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.

lr_scheduler:
  type: MultiStepLR
  milestones: [80, 100]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearLR
  start_factor: 0.001
  total_iters: 1000

# Loss and training settings
weight_dict:
  loss_vfl: 1
  loss_bbox: 5  
  loss_giou: 2

ema:
  decay: 0.9999
  warmups: 2000

# Load pretrained weights for transfer learning
tuning: '/home/ewan/omlet-server-egg-det/weights/rtdetrv2_r18vd_120e_coco_rerun_48.1.pth'